package GUI;

import Models.CTHoaDonTam;
import Models.DichVu;
import Models.LoaiPhong;
import Models.Phong;
import Services.DichVuService;
import Services.CTDichVuService;
import Services.LoaiDichVuService;
import Services.LoaiPhongService;
import Services.PhongService;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Models.LoaiDichVu;
import Models.CTDichVu;
import Models.HoaDon;
import Models.ThanhToan;
import Models.TrangThaiThanhToan;
import Services.ThanhToanService;
import Services.TrangThaiPhongService;
import Services.TrangThaiThanhToanService;

public class MainFrame extends javax.swing.JFrame {

    CardLayout card;
    int index;
    Thread tbd, tkt, d;
    LoaiDichVuService ldvs = new LoaiDichVuService();
    DichVuService dvs = new DichVuService();
    TrangThaiPhongService ttps = new TrangThaiPhongService();
    ThanhToanService tts = new ThanhToanService();
    TrangThaiThanhToanService tttts = new TrangThaiThanhToanService();
    
    ArrayList<CTHoaDonTam> list = new ArrayList();

    public MainFrame() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        timeBD();
        timKT();
        dateNow();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgnChucvu = new javax.swing.ButtonGroup();
        bgnTrangthai = new javax.swing.ButtonGroup();
        bgnTTDV = new javax.swing.ButtonGroup();
        jDialogXemCT = new javax.swing.JDialog();
        jPanel37 = new javax.swing.JPanel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        txtMaLPXTC = new javax.swing.JTextField();
        txtTangXTC = new javax.swing.JTextField();
        txtTrangThaiXTC = new javax.swing.JTextField();
        txtLoaiPhongXTC = new javax.swing.JTextField();
        txtGiaTheoGioXTC = new javax.swing.JTextField();
        jLabel95 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDonCT1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDonCT2 = new javax.swing.JTable();
        jPanel41 = new javax.swing.JPanel();
        jDialogTaoHD = new javax.swing.JDialog();
        jPanel42 = new javax.swing.JPanel();
        lblPhongHD = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        txtMaLPHD = new javax.swing.JTextField();
        txtTangHD = new javax.swing.JTextField();
        txtTrangThaiHD = new javax.swing.JTextField();
        txtLoaiPhongHD = new javax.swing.JTextField();
        txtGiaTheoGioHD = new javax.swing.JTextField();
        jLabel105 = new javax.swing.JLabel();
        txtTenKHHD = new javax.swing.JTextField();
        jLabel104 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDichVuCS = new javax.swing.JTable();
        jPanel44 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnuXemCT = new javax.swing.JMenuItem();
        mnuTaoDH = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuThemDV = new javax.swing.JMenuItem();
        jDialogThemDV = new javax.swing.JDialog();
        jPanel45 = new javax.swing.JPanel();
        jLabel114 = new javax.swing.JLabel();
        lblPhongThemHD = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        txtMaLPTDV = new javax.swing.JTextField();
        txtTangTDV = new javax.swing.JTextField();
        txtTrangThaiTDV = new javax.swing.JTextField();
        txtLoaiPhongTDV = new javax.swing.JTextField();
        txtGiaTheoGioTDV = new javax.swing.JTextField();
        jLabel113 = new javax.swing.JLabel();
        txtTenKHTDV = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLoaiDV = new javax.swing.JTable();
        jLabel115 = new javax.swing.JLabel();
        cboLoaiDV = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDVHienDung = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnHoanThanh = new javax.swing.JButton();
        jLabel116 = new javax.swing.JLabel();
        lblAnTrom = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnCardGoc = new javax.swing.JPanel();
        pnCardManChinh = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlTang1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblTang1 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblTang2 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblTang3 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        lblTimeBD = new javax.swing.JLabel();
        lblTimeKT = new javax.swing.JLabel();
        btnBatDau = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        lblNgay = new javax.swing.JLabel();
        lblTangThai = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        cboHTTT = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        cboTrangThai = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnManChinh = new javax.swing.JButton();
        btnTaiKhoan = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnPhong = new javax.swing.JButton();
        btnDichVu = new javax.swing.JButton();
        btnGioiThieu = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        tnGhiChuNhanh = new javax.swing.JButton();

        jPanel37.setBackground(new java.awt.Color(254, 204, 213));

        jLabel88.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel88.setText("PHÒNG 101");

        jLabel89.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel89.setText("Hóa đơn chi tiết");

        jPanel40.setBackground(new java.awt.Color(255, 255, 255));

        jLabel90.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel90.setText("Mã loại phòng");

        jLabel91.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel91.setText("Tầng");

        jLabel92.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel92.setText("Trạng thái");

        jLabel93.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel93.setText("Loại phòng");

        jLabel94.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel94.setText("Giá theo giờ");

        txtMaLPXTC.setEditable(false);
        txtMaLPXTC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTangXTC.setEditable(false);
        txtTangXTC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTrangThaiXTC.setEditable(false);
        txtTrangThaiXTC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtLoaiPhongXTC.setEditable(false);
        txtLoaiPhongXTC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtGiaTheoGioXTC.setEditable(false);
        txtGiaTheoGioXTC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel91)
                    .addComponent(jLabel90)
                    .addComponent(jLabel92))
                .addGap(34, 34, 34)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaLPXTC, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTangXTC, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel40Layout.createSequentialGroup()
                                .addComponent(jLabel94)
                                .addGap(18, 18, 18)
                                .addComponent(txtGiaTheoGioXTC, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel40Layout.createSequentialGroup()
                                .addComponent(jLabel93)
                                .addGap(26, 26, 26)
                                .addComponent(txtLoaiPhongXTC, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtTrangThaiXTC, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel90)
                    .addComponent(jLabel93)
                    .addComponent(txtMaLPXTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoaiPhongXTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel91)
                    .addComponent(jLabel94)
                    .addComponent(txtTangXTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTheoGioXTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel92)
                    .addComponent(txtTrangThaiXTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel95.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel95.setText("Chi tiết phòng");

        tblHoaDonCT1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên dịch vụ", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHoaDonCT1);

        tblHoaDonCT2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số giờ", "Thành tiền", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblHoaDonCT2);

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel37Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel88)
                .addGap(341, 341, 341))
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel37Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel89))
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel95)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel88)
                .addGap(9, 9, 9)
                .addComponent(jLabel95)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel89)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jDialogXemCTLayout = new javax.swing.GroupLayout(jDialogXemCT.getContentPane());
        jDialogXemCT.getContentPane().setLayout(jDialogXemCTLayout);
        jDialogXemCTLayout.setHorizontalGroup(
            jDialogXemCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogXemCTLayout.setVerticalGroup(
            jDialogXemCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel42.setBackground(new java.awt.Color(254, 204, 213));

        lblPhongHD.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        lblPhongHD.setText("PHÒNG 101");

        jLabel97.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel97.setText("Dịch vụ có sẵn");

        jPanel43.setBackground(new java.awt.Color(255, 255, 255));

        jLabel98.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel98.setText("Mã loại phòng");

        jLabel99.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel99.setText("Tầng");

        jLabel101.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel101.setText("Trạng thái");

        jLabel102.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel102.setText("Loại phòng");

        jLabel103.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel103.setText("Giá theo giờ");

        txtMaLPHD.setEditable(false);
        txtMaLPHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTangHD.setEditable(false);
        txtTangHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTrangThaiHD.setEditable(false);
        txtTrangThaiHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtLoaiPhongHD.setEditable(false);
        txtLoaiPhongHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtGiaTheoGioHD.setEditable(false);
        txtGiaTheoGioHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel105.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel105.setText("Tên khách hàng");

        txtTenKHHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel99)
                    .addComponent(jLabel98)
                    .addComponent(jLabel101))
                .addGap(34, 34, 34)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaLPHD, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTangHD, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrangThaiHD, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addComponent(jLabel105)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(txtTenKHHD, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addComponent(jLabel102)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLoaiPhongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addComponent(jLabel103)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGiaTheoGioHD, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel98)
                    .addComponent(jLabel102)
                    .addComponent(txtMaLPHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoaiPhongHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel99)
                    .addComponent(jLabel103)
                    .addComponent(txtTangHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTheoGioHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel101)
                    .addComponent(txtTrangThaiHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel105)
                    .addComponent(txtTenKHHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel104.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel104.setText("Chi tiết phòng");

        tblDichVuCS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã DV", "Tên DV", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblDichVuCS);

        jPanel44.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton3.setText("Xoá dịch vụ khỏi phòng");

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton4.setText("Tạo hoá đơn");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(lblPhongHD))
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel97))
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel42Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel104)))))
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jButton3)
                        .addGap(47, 47, 47)
                        .addComponent(jButton4)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel42Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton3, jButton4});

        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblPhongHD)
                .addGap(18, 18, 18)
                .addComponent(jLabel104)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel97)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel42Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton3, jButton4});

        javax.swing.GroupLayout jDialogTaoHDLayout = new javax.swing.GroupLayout(jDialogTaoHD.getContentPane());
        jDialogTaoHD.getContentPane().setLayout(jDialogTaoHDLayout);
        jDialogTaoHDLayout.setHorizontalGroup(
            jDialogTaoHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTaoHDLayout.createSequentialGroup()
                .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialogTaoHDLayout.setVerticalGroup(
            jDialogTaoHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mnuXemCT.setText("jMenuItem1");
        mnuXemCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuXemCTActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuXemCT);

        mnuTaoDH.setText("jMenuItem2");
        mnuTaoDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTaoDHActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuTaoDH);
        jPopupMenu1.add(jSeparator1);

        mnuThemDV.setText("jMenuItem3");
        mnuThemDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThemDVActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuThemDV);

        jPanel45.setBackground(new java.awt.Color(254, 204, 213));

        jLabel114.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel114.setText("DỊCH VỤ HIỆN DÙNG");

        lblPhongThemHD.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        lblPhongThemHD.setText("PHÒNG 101");

        jPanel46.setBackground(new java.awt.Color(255, 255, 255));

        jLabel108.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel108.setText("Mã loại phòng");

        jLabel109.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel109.setText("Tầng");

        jLabel110.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel110.setText("Trạng thái");

        jLabel111.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel111.setText("Loại phòng");

        jLabel112.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel112.setText("Giá theo giờ");

        txtMaLPTDV.setEditable(false);
        txtMaLPTDV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTangTDV.setEditable(false);
        txtTangTDV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTrangThaiTDV.setEditable(false);
        txtTrangThaiTDV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtLoaiPhongTDV.setEditable(false);
        txtLoaiPhongTDV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtGiaTheoGioTDV.setEditable(false);
        txtGiaTheoGioTDV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel113.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel113.setText("Tên khách hàng");

        txtTenKHTDV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel109)
                    .addComponent(jLabel108)
                    .addComponent(jLabel110))
                .addGap(34, 34, 34)
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaLPTDV, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTangTDV, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrangThaiTDV, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel46Layout.createSequentialGroup()
                        .addComponent(jLabel113)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(txtTenKHTDV, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel46Layout.createSequentialGroup()
                        .addComponent(jLabel111)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLoaiPhongTDV, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel46Layout.createSequentialGroup()
                        .addComponent(jLabel112)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGiaTheoGioTDV, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel108)
                    .addComponent(jLabel111)
                    .addComponent(txtMaLPTDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoaiPhongTDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel109)
                    .addComponent(jLabel112)
                    .addComponent(txtTangTDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTheoGioTDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel110)
                    .addComponent(txtTrangThaiTDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel113)
                    .addComponent(txtTenKHTDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tblLoaiDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã DV", "Tên DV", "Số lượng", "Đơn vị", "Trạng thái"
            }
        ));
        jScrollPane4.setViewportView(tblLoaiDV);

        jLabel115.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel115.setText("Loại dịch vụ");

        cboLoaiDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiDVActionPerformed(evt);
            }
        });

        tblDVHienDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã DV", "Tên DV", "Số lượng"
            }
        ));
        jScrollPane5.setViewportView(tblDVHienDung);

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnHoanThanh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnHoanThanh.setText("Hoàn thành");

        jLabel116.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel116.setText("Chi tiết phòng");

        lblAnTrom.setText("jLabel1");

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel45Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel45Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel114))
                            .addComponent(jPanel46, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel45Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel116))
                            .addComponent(jScrollPane4)))
                    .addGroup(jPanel45Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(lblPhongThemHD))
                    .addGroup(jPanel45Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel115)
                        .addGap(43, 43, 43)
                        .addComponent(cboLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel45Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(btnThem)
                        .addGap(42, 42, 42)
                        .addComponent(btnHoanThanh))
                    .addComponent(lblAnTrom, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        jPanel45Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHoanThanh, btnThem});

        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel45Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhongThemHD)
                .addGap(10, 10, 10)
                .addComponent(jLabel116)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel114)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel115, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoanThanh)
                    .addComponent(btnThem))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lblAnTrom, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jDialogThemDVLayout = new javax.swing.GroupLayout(jDialogThemDV.getContentPane());
        jDialogThemDV.getContentPane().setLayout(jDialogThemDVLayout);
        jDialogThemDVLayout.setHorizontalGroup(
            jDialogThemDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogThemDVLayout.setVerticalGroup(
            jDialogThemDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogThemDVLayout.createSequentialGroup()
                .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý karaoke - Trang chủ");

        jPanel1.setBackground(new java.awt.Color(254, 204, 213));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        pnCardGoc.setBackground(new java.awt.Color(254, 204, 213));
        pnCardGoc.setLayout(new java.awt.CardLayout());

        pnCardManChinh.setBackground(new java.awt.Color(254, 204, 213));
        pnCardManChinh.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        jPanel4.setBackground(new java.awt.Color(254, 204, 213));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        pnlTang1.setBackground(new java.awt.Color(254, 204, 213));
        pnlTang1.setLayout(new java.awt.GridLayout(1, 1, 15, 15));

        tblTang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phòng", "Loại phòng", "Khách hàng", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTang1.setComponentPopupMenu(jPopupMenu1);
        tblTang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTang1MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblTang1);

        pnlTang1.add(jScrollPane6);

        jTabbedPane1.addTab("Tầng 1", pnlTang1);

        jPanel8.setBackground(new java.awt.Color(254, 204, 213));
        jPanel8.setLayout(new java.awt.GridLayout(1, 1, 15, 15));

        tblTang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phòng", "Loại phòng", "Khách hàng", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTang2.setComponentPopupMenu(jPopupMenu1);
        tblTang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTang2MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblTang2);

        jPanel8.add(jScrollPane7);

        jTabbedPane1.addTab("Tầng 2", jPanel8);

        jPanel9.setBackground(new java.awt.Color(254, 204, 213));
        jPanel9.setLayout(new java.awt.GridLayout(1, 1, 15, 15));

        tblTang3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phòng", "Loại phòng", "Khách hàng", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTang3.setComponentPopupMenu(jPopupMenu1);
        tblTang3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTang3MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblTang3);

        jPanel9.add(jScrollPane8);

        jTabbedPane1.addTab("Tầng 3", jPanel9);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        pnCardManChinh.add(jPanel4);

        jPanel2.setBackground(new java.awt.Color(254, 204, 213));

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));
        jPanel35.setLayout(new java.awt.GridLayout(1, 3));

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel36.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTimeBD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTimeBD.setText("19:05:35");

        lblTimeKT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTimeKT.setText("__:__:__");

        btnBatDau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBatDau.setText("Bắt đầu");
        btnBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatDauActionPerformed(evt);
            }
        });

        btnKetThuc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKetThuc.setText("Kết thúc");
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });

        lblNgay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNgay.setText("11/10/2021");

        lblTangThai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTangThai.setText("Trống");

        jLabel100.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel100.setText("Trạng thái:");

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel36Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgay)
                    .addComponent(lblTimeKT)
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addComponent(jLabel100)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTangThai))
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addComponent(lblTimeBD)
                        .addGap(114, 114, 114)
                        .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBatDau)
                            .addComponent(btnKetThuc))))
                .addGap(108, 108, 108))
        );

        jPanel36Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatDau, btnKetThuc});

        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimeBD)
                    .addComponent(btnBatDau))
                .addGap(18, 18, 18)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTimeKT)
                    .addComponent(btnKetThuc))
                .addGap(18, 18, 18)
                .addComponent(lblNgay)
                .addGap(18, 18, 18)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel100)
                    .addComponent(lblTangThai))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel35.add(jPanel36);

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setLayout(new java.awt.GridLayout(6, 1));

        jLabel82.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel82.setText("Tổng số giờ hát:");
        jPanel38.add(jLabel82);

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel83.setText("Tiền cần thanh toán");
        jPanel38.add(jLabel83);

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel84.setText("Tiền khách đưa");
        jPanel38.add(jLabel84);

        jLabel85.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel85.setText("Hình thức thanh toán");
        jPanel38.add(jLabel85);

        jLabel86.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel86.setText("Tiền trả khách");
        jPanel38.add(jLabel86);

        jLabel87.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel87.setText("Trạng thái");
        jPanel38.add(jLabel87);

        jPanel35.add(jPanel38);

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setLayout(new java.awt.GridLayout(6, 1, 0, 15));
        jPanel39.add(jTextField1);
        jPanel39.add(jTextField2);
        jPanel39.add(jTextField3);

        cboHTTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel39.add(cboHTTT);
        jPanel39.add(jTextField4);

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel39.add(cboTrangThai);

        jPanel35.add(jPanel39);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("THANH TOÁN");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("ĐỔI PHÒNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, 1439, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pnCardManChinh.add(jPanel2);

        pnCardGoc.add(pnCardManChinh, "card1");

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        btnManChinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManChinh.setText("Màn chính");
        btnManChinh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnManChinh.setFocusable(false);
        btnManChinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManChinh.setMargin(new java.awt.Insets(2, 14, 2, 85));
        btnManChinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManChinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManChinhActionPerformed(evt);
            }
        });
        jToolBar1.add(btnManChinh);

        btnTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTaiKhoan.setText("Tài khoản");
        btnTaiKhoan.setFocusable(false);
        btnTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTaiKhoan.setMargin(new java.awt.Insets(2, 14, 2, 85));
        btnTaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTaiKhoan);

        btnKhachHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKhachHang.setText("Khách hàng");
        btnKhachHang.setFocusable(false);
        btnKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhachHang.setMargin(new java.awt.Insets(2, 14, 2, 85));
        btnKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhachHang);

        btnPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPhong.setText("Phòng");
        btnPhong.setFocusable(false);
        btnPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPhong.setMargin(new java.awt.Insets(2, 14, 2, 85));
        btnPhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPhong);

        btnDichVu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDichVu.setText("Dịch vụ");
        btnDichVu.setFocusable(false);
        btnDichVu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDichVu.setMargin(new java.awt.Insets(2, 14, 2, 85));
        btnDichVu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichVuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDichVu);

        btnGioiThieu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGioiThieu.setText("Giới thiệu");
        btnGioiThieu.setFocusable(false);
        btnGioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGioiThieu.setMargin(new java.awt.Insets(2, 14, 2, 85));
        btnGioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGioiThieuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGioiThieu);

        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThongKe.setText("Thống kê doanh thu");
        btnThongKe.setFocusable(false);
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setMargin(new java.awt.Insets(2, 14, 2, 85));
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThongKe);

        tnGhiChuNhanh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tnGhiChuNhanh.setText("Ghi chú nhanh");
        tnGhiChuNhanh.setFocusable(false);
        tnGhiChuNhanh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tnGhiChuNhanh.setMargin(new java.awt.Insets(2, 14, 2, 85));
        tnGhiChuNhanh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tnGhiChuNhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnGhiChuNhanhActionPerformed(evt);
            }
        });
        jToolBar1.add(tnGhiChuNhanh);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnCardGoc, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnCardGoc, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        JFrameTaiKhoan frmTK = new JFrameTaiKhoan();
        frmTK.setVisible(true);
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongActionPerformed
        JFramePhong frmP = new JFramePhong();
        frmP.setVisible(true);
    }//GEN-LAST:event_btnPhongActionPerformed

    private void btnManChinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManChinhActionPerformed

    }//GEN-LAST:event_btnManChinhActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        JFrameKhachHang frmKH = new JFrameKhachHang();
        frmKH.setVisible(true);
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichVuActionPerformed
        JFrameDichVu frmDV = new JFrameDichVu();
        frmDV.setVisible(true);
    }//GEN-LAST:event_btnDichVuActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        JFrameThongKe frmTK = new JFrameThongKe();
        frmTK.setVisible(true);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatDauActionPerformed
        // TODO add your handling code here:
        tbd.stop();
        layTime();
    }//GEN-LAST:event_btnBatDauActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        // TODO add your handling code here:
        tkt.stop();
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void mnuXemCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuXemCTActionPerformed
        jDialogXemCT.show();
    }//GEN-LAST:event_mnuXemCTActionPerformed

    private void mnuTaoDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTaoDHActionPerformed
        jDialogTaoHD.show();
    }//GEN-LAST:event_mnuTaoDHActionPerformed

    private void mnuThemDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThemDVActionPerformed
        // TODO add your handling code here:
        jDialogThemDV.show();
    }//GEN-LAST:event_mnuThemDVActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGioiThieuActionPerformed
        // TODO add your handling code here:
        JFrameGioiThieu jfrGT = new JFrameGioiThieu();
        jfrGT.setVisible(true);
    }//GEN-LAST:event_btnGioiThieuActionPerformed

    private void tnGhiChuNhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnGhiChuNhanhActionPerformed
        JFrameGhiChu jfrGhiChu = new JFrameGhiChu();
        jfrGhiChu.setVisible(true);
    }//GEN-LAST:event_tnGhiChuNhanhActionPerformed

    private void tblTang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTang1MouseClicked
        if (evt.getClickCount() == 1) {
            this.index = tblTang1.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                show1();
            }
        }
    }//GEN-LAST:event_tblTang1MouseClicked

    private void tblTang2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTang2MouseClicked
        if (evt.getClickCount() == 1) {
            this.index = tblTang2.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                show2();
            }
        }
    }//GEN-LAST:event_tblTang2MouseClicked

    private void tblTang3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTang3MouseClicked
        if (evt.getClickCount() == 1) {
            this.index = tblTang3.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                show3();
            }
        }
    }//GEN-LAST:event_tblTang3MouseClicked

    private void cboLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiDVActionPerformed
        // TODO add your handling code here:
        fillToTableDichVu();
    }//GEN-LAST:event_cboLoaiDVActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if(txtTenKHHD.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Chưa nhập khách hàng!!!");
           return;
       }else{
           taoHD();
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgnChucvu;
    private javax.swing.ButtonGroup bgnTTDV;
    private javax.swing.ButtonGroup bgnTrangthai;
    private javax.swing.JButton btnBatDau;
    private javax.swing.JButton btnDichVu;
    private javax.swing.JButton btnGioiThieu;
    private javax.swing.JButton btnHoanThanh;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnManChinh;
    private javax.swing.JButton btnPhong;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JComboBox<String> cboHTTT;
    private javax.swing.JComboBox<String> cboLoaiDV;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialogTaoHD;
    private javax.swing.JDialog jDialogThemDV;
    private javax.swing.JDialog jDialogXemCT;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAnTrom;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblPhongHD;
    private javax.swing.JLabel lblPhongThemHD;
    private javax.swing.JLabel lblTangThai;
    private javax.swing.JLabel lblTimeBD;
    private javax.swing.JLabel lblTimeKT;
    private javax.swing.JMenuItem mnuTaoDH;
    private javax.swing.JMenuItem mnuThemDV;
    private javax.swing.JMenuItem mnuXemCT;
    private javax.swing.JPanel pnCardGoc;
    private javax.swing.JPanel pnCardManChinh;
    private javax.swing.JPanel pnlTang1;
    private javax.swing.JTable tblDVHienDung;
    private javax.swing.JTable tblDichVuCS;
    private javax.swing.JTable tblHoaDonCT1;
    private javax.swing.JTable tblHoaDonCT2;
    private javax.swing.JTable tblLoaiDV;
    private javax.swing.JTable tblTang1;
    private javax.swing.JTable tblTang2;
    private javax.swing.JTable tblTang3;
    private javax.swing.JButton tnGhiChuNhanh;
    private javax.swing.JTextField txtGiaTheoGioHD;
    private javax.swing.JTextField txtGiaTheoGioTDV;
    private javax.swing.JTextField txtGiaTheoGioXTC;
    private javax.swing.JTextField txtLoaiPhongHD;
    private javax.swing.JTextField txtLoaiPhongTDV;
    private javax.swing.JTextField txtLoaiPhongXTC;
    private javax.swing.JTextField txtMaLPHD;
    private javax.swing.JTextField txtMaLPTDV;
    private javax.swing.JTextField txtMaLPXTC;
    private javax.swing.JTextField txtTangHD;
    private javax.swing.JTextField txtTangTDV;
    private javax.swing.JTextField txtTangXTC;
    private javax.swing.JTextField txtTenKHHD;
    private javax.swing.JTextField txtTenKHTDV;
    private javax.swing.JTextField txtTrangThaiHD;
    private javax.swing.JTextField txtTrangThaiTDV;
    private javax.swing.JTextField txtTrangThaiXTC;
    // End of variables declaration//GEN-END:variables

    private void timeBD() {
        tbd = new Thread() {
            @Override
            public void run() {
                SimpleDateFormat date = new SimpleDateFormat("hh:mm:ss");
                while (true) {
                    Date d = new Date();
                    lblTimeBD.setText(date.format(d));
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        break;
                    }
                }
            }

        };
        tbd.start();
    }

    private void timKT() {
        tkt = new Thread() {
            @Override
            public void run() {
                SimpleDateFormat date = new SimpleDateFormat("hh:mm:ss");
                while (true) {
                    Date d = new Date();
                    lblTimeKT.setText(date.format(d));
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        break;
                    }
                }
            }

        };
        tkt.start();
    }

    private void dateNow() {
        d = new Thread() {
            @Override
            public void run() {
                SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
                while (true) {
                    Date d = new Date();
                    lblNgay.setText("Ngày: " + date.format(d));
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        break;
                    }
                }
            }

        };
        d.start();
    }

    PhongService ps = new PhongService();

    private void init() {
        mnuXemCT.setText("Xem chi tiết");
        mnuTaoDH.setText("Tạo hóa đơn");
        mnuThemDV.setText("Thêm dịch vụ");
        jDialogXemCT.setSize(870, 800);
        jDialogXemCT.setTitle("Quản lý Karaoke - Xem chi tiết");
        jDialogTaoHD.setSize(900, 700);
        jDialogTaoHD.setTitle("Quản lý Karaoke - Tạo hóa đơn");
        jDialogThemDV.setSize(870, 800);
        jDialogThemDV.setTitle("Quản lý Karaoke - Thêm dịch vụ");
        fillTable1();
        fillTable2();
        fillTable3();
        FillDichVuCS();
        fillToComboDichVu();
        fillToTableDichVuHD();
        fillToComboHinhThucTT();
        fillToComboTrangThaiHD();
    }
//    public String getTT(Phong p){
//        List<TrangThaiPhong> listtp = ttps.selectAll();
//        for (TrangThaiPhong tt:listtp) {
//            if(p.getTrangThai()==tt.getIdTTPhong()){
//                return tt.getTenTTPhong();
//            }
//            return tt.getTenTTPhong();
//        }
//        return "";
//    }

    private void fillTable1() {
        DefaultTableModel model1 = (DefaultTableModel) tblTang1.getModel();
        model1.setRowCount(0);
        try {
            List<LoaiPhong> lstLP = lps.selectAll();
            for (LoaiPhong lp : lstLP) {
                List<Phong> lst1 = ps.selectByTang(1);
                for (Phong p : lst1) {
                    if (lp.getMaLP().equals(p.getMaLP())) {
                        Object[] row = {
                            p.getMaP(),
                            lp.getTenLP(),
                            p.kh = txtTenKHHD.getText(),
                            p.getTrangThai()
                        };
                        model1.addRow(row);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillTable2() {
        DefaultTableModel model1 = (DefaultTableModel) tblTang2.getModel();
        model1.setRowCount(0);
        try {
            List<LoaiPhong> lstLP = lps.selectAll();
            for (LoaiPhong lp : lstLP) {
                List<Phong> lst1 = ps.selectByTang(2);
                for (Phong p : lst1) {
                    if (lp.getMaLP().equals(p.getMaLP())) {
                        Object[] row = {
                            p.getMaP(),
                            lp.getTenLP(),
                            p.kh = txtTenKHHD.getText(),
                            p.getTrangThai()
                        };
                        model1.addRow(row);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillTable3() {
        DefaultTableModel model1 = (DefaultTableModel) tblTang3.getModel();
        model1.setRowCount(0);
        try {
            List<LoaiPhong> lstLP = lps.selectAll();
            for (LoaiPhong lp : lstLP) {
                List<Phong> lst1 = ps.selectByTang(3);
                for (Phong p : lst1) {
                    if (lp.getMaLP().equals(p.getMaLP())) {
                        Object[] row = {
                            p.getMaP(),
                            lp.getTenLP(),
                            p.kh = txtTenKHHD.getText(),
                            p.getTrangThai()
                        };
                        model1.addRow(row);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    LoaiPhongService lps = new LoaiPhongService();

    private void show1() {
        try {
            String map = (String) tblTang1.getValueAt(index, 0);
            Phong model = ps.selectByID(map);
            if (model != null) {
                this.setModelTaoHD(model);
                this.setModelThemDV(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi Show1");
            e.printStackTrace();
        }
    }

    private void show2() {
        try {
            String map = (String) tblTang2.getValueAt(index, 0);
            Phong model = ps.selectByID(map);
            if (model != null) {
                this.setModelTaoHD(model);
                this.setModelThemDV(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi Show1");
            e.printStackTrace();
        }
    }

    private void show3() {
        try {
            String map = (String) tblTang3.getValueAt(index, 0);
            Phong model = ps.selectByID(map);
            if (model != null) {
                this.setModelTaoHD(model);
                this.setModelThemDV(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi Show1");
            e.printStackTrace();
        }
    }

    void setModelTaoHD(Phong model) {
        lblAnTrom.setText(model.getMaP());
        lblPhongHD.setText("Phòng " + model.getMaP());
        txtMaLPHD.setText(model.getMaLP()+"");
        String malp = txtMaLPHD.getText();
        LoaiPhong lp = lps.selectByID(malp);
        txtTangHD.setText(model.getTang() + "");
        txtTrangThaiHD.setText(model.getTrangThai() + "");
        txtLoaiPhongHD.setText(lp.getTenLP());
        txtGiaTheoGioHD.setText(lp.getGiaTheoGio() + "");
    }

    void setModelThemDV(Phong model) {
        lblPhongThemHD.setText("Phòng " + model.getMaP());
        txtMaLPTDV.setText(model.getMaLP()+"");
        String malp = txtMaLPTDV.getText();
        LoaiPhong lp = lps.selectByID(malp);
        txtTangTDV.setText(model.getTang() + "");
        txtTrangThaiTDV.setText(model.getTrangThai() + "");
        txtLoaiPhongTDV.setText(lp.getTenLP());
        txtGiaTheoGioTDV.setText(lp.getGiaTheoGio() + "");
    }

    private void FillDichVuCS() {
        DefaultTableModel model1 = (DefaultTableModel) tblDichVuCS.getModel();
        model1.setRowCount(0);
        try {
            List<DichVu> lstComBoDV = dvs.selectDVCS();
            for (DichVu dv : lstComBoDV) {
                Object[] row = {
                    dv.getMaDV(),
                    dv.getTenDV(),
                    dv.getSoLuong()
                };
                model1.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillToComboDichVu() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiDV.getModel();
        model.removeAllElements();
        List<LoaiDichVu> listcb = ldvs.selectAll();
        for (LoaiDichVu ldv : listcb) {
            model.addElement(ldv);
        }
    }

    private void fillToTableDichVu() {
        DefaultTableModel model_dv = (DefaultTableModel) tblLoaiDV.getModel();
        model_dv.setRowCount(0);
        try {
            LoaiDichVu loaidv = (LoaiDichVu) cboLoaiDV.getSelectedItem();
            List<DichVu> listdv = dvs.selectByLoaiDV(loaidv.getMaLDV());
            for (DichVu dv : listdv) {
                Object[] row = {
                    dv.getMaDV(),
                    dv.getTenDV(),
                    dv.getSoLuong(),
                    dv.getDonViTinh(),
                    dv.getTrangThai()
                };
                model_dv.addRow(row);
            }
        } catch (Exception e) {
        }
    }

    CTDichVuService ctdv = new CTDichVuService();

    private void fillToTableDichVuHD() {
        DefaultTableModel model_dv = (DefaultTableModel) tblDVHienDung.getModel();
        model_dv.setRowCount(0);
        try {
            List<CTDichVu> listctdv = ctdv.selectAll();
            for (CTDichVu dv : listctdv) {
                Object[] row = {
                    dv.getMaDV(),
                    dv.getTenDV(),
                    dv.getSoLuong()
                };
                model_dv.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillToComboHinhThucTT() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboHTTT.getModel();
        model.removeAllElements();
        List<ThanhToan> listtt = tts.selectAll();
        for (ThanhToan tt : listtt) {
            model.addElement(tt);
        }
    }
    
    private void fillToComboTrangThaiHD() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTrangThai.getModel();
        model.removeAllElements();
        List<TrangThaiThanhToan> listtttt = tttts.selectAll();
        for (TrangThaiThanhToan tttt : listtttt) {
            model.addElement(tttt);
        }
    }

    private void layTime() {
        
    }

    private void taoHD() {
        List<HoaDon> listHD = new ArrayList();
        
    }
    
    
}
