package GUI;

import Models.CTHoaDonTam;
import Models.DichVu;
import Models.LoaiPhong;
import Models.Phong;
import Services.DichVuService;
import Services.CTDichVuService;
import Services.LoaiDichVuService;
import Services.LoaiPhongService;
import Services.PhongService;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Models.LoaiDichVu;
import Models.CTDichVu;
import Models.HoaDon;
import Models.HoaDonChiTiet;
import Models.KhachHang;
import Models.ThanhToan;
import Models.TrangThaiPhong;
import Models.TrangThaiThanhToan;
import Services.HoaDonChiTietService;
import Services.HoaDonService;
import Services.KhachHangService;
import Services.ThanhToanService;
import Services.TrangThaiPhongService;
import Services.TrangThaiThanhToanService;
import Utilities.UseUtilies;
import Utilities.dateUtilities;

public class MainFrame extends javax.swing.JFrame {

    CardLayout card;
    int index;
    Thread tbd, tkt, d;
    LoaiDichVuService ldvs = new LoaiDichVuService();
    DichVuService dvs = new DichVuService();
    TrangThaiPhongService ttps = new TrangThaiPhongService();
    ThanhToanService tts = new ThanhToanService();
    TrangThaiThanhToanService tttts = new TrangThaiThanhToanService();
    HoaDonChiTietService hdcts = new HoaDonChiTietService();

    ArrayList<CTHoaDonTam> list = new ArrayList();

    public MainFrame() {
        initComponents();
        timeBD();
        timKT();
        dateNow();
        init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgnChucvu = new javax.swing.ButtonGroup();
        bgnTrangthai = new javax.swing.ButtonGroup();
        bgnTTDV = new javax.swing.ButtonGroup();
        jDialogTaoHD = new javax.swing.JDialog();
        jPanel42 = new javax.swing.JPanel();
        lblPhongHD = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        txtMaLPHD = new javax.swing.JTextField();
        txtTangHD = new javax.swing.JTextField();
        txtTrangThaiHD = new javax.swing.JTextField();
        txtLoaiPhongHD = new javax.swing.JTextField();
        txtGiaTheoGioHD = new javax.swing.JTextField();
        jLabel105 = new javax.swing.JLabel();
        cboKhachHang = new javax.swing.JComboBox<>();
        jLabel104 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDichVuCS = new javax.swing.JTable();
        jPanel44 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        btnTaoHoaDon = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnuTaoDH = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblMaPhong = new javax.swing.JLabel();
        pnCardGoc = new javax.swing.JPanel();
        pnCardManChinh = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tabTang = new javax.swing.JTabbedPane();
        pnlTang1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblTang1 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblTang2 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblTang3 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnHuyDV = new javax.swing.JButton();
        btnCapNhap = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblDVCP = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        btnThemVaoP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cboDichVu = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblGioDung = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTienCanTT = new javax.swing.JTextField();
        txtTienKhachDua = new javax.swing.JTextField();
        txtTienTraKhach = new javax.swing.JTextField();
        btnDoiPhong = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        cboHinhThucThanhToan = new javax.swing.JComboBox<>();
        cboTrangThaiHoaDon = new javax.swing.JComboBox<>();
        btnTraPhong = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblMaHD = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jPanel42.setBackground(new java.awt.Color(254, 204, 213));

        lblPhongHD.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        lblPhongHD.setText("PHÒNG 101");

        jLabel97.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel97.setText("Dịch vụ có sẵn");

        jPanel43.setBackground(new java.awt.Color(255, 255, 255));

        jLabel98.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel98.setText("Mã loại phòng");

        jLabel99.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel99.setText("Tầng");

        jLabel101.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel101.setText("Trạng thái");

        jLabel102.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel102.setText("Loại phòng");

        jLabel103.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel103.setText("Giá theo giờ");

        txtMaLPHD.setEditable(false);
        txtMaLPHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTangHD.setEditable(false);
        txtTangHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTrangThaiHD.setEditable(false);
        txtTrangThaiHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtLoaiPhongHD.setEditable(false);
        txtLoaiPhongHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtGiaTheoGioHD.setEditable(false);
        txtGiaTheoGioHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel105.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel105.setText("Tên khách hàng");

        cboKhachHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel99)
                    .addComponent(jLabel98)
                    .addComponent(jLabel101))
                .addGap(34, 34, 34)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaLPHD, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTangHD, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrangThaiHD, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addComponent(jLabel102)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(txtLoaiPhongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel43Layout.createSequentialGroup()
                        .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel103)
                            .addComponent(jLabel105))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGiaTheoGioHD, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(cboKhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(34, 34, 34))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel98)
                    .addComponent(jLabel102)
                    .addComponent(txtMaLPHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoaiPhongHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel99)
                    .addComponent(jLabel103)
                    .addComponent(txtTangHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTheoGioHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel101)
                        .addComponent(txtTrangThaiHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel105))
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addComponent(cboKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel104.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel104.setText("Chi tiết phòng");

        tblDichVuCS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã DV", "Tên DV", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblDichVuCS);

        jPanel44.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton3.setText("Xoá dịch vụ khỏi phòng");

        btnTaoHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        btnTaoHoaDon.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnTaoHoaDon.setText("Tạo hoá đơn");
        btnTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(lblPhongHD))
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel97))
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel42Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel104)))))
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jButton3)
                        .addGap(47, 47, 47)
                        .addComponent(btnTaoHoaDon)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel42Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnTaoHoaDon, jButton3});

        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblPhongHD)
                .addGap(18, 18, 18)
                .addComponent(jLabel104)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel97)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTaoHoaDon)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel42Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnTaoHoaDon, jButton3});

        javax.swing.GroupLayout jDialogTaoHDLayout = new javax.swing.GroupLayout(jDialogTaoHD.getContentPane());
        jDialogTaoHD.getContentPane().setLayout(jDialogTaoHDLayout);
        jDialogTaoHDLayout.setHorizontalGroup(
            jDialogTaoHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTaoHDLayout.createSequentialGroup()
                .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialogTaoHDLayout.setVerticalGroup(
            jDialogTaoHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mnuTaoDH.setText("jMenuItem2");
        mnuTaoDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTaoDHActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuTaoDH);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý karaoke - Trang chủ");
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(254, 204, 213));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblMaPhong.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(lblMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnCardGoc.setBackground(new java.awt.Color(254, 204, 213));
        pnCardGoc.setLayout(new java.awt.CardLayout());

        pnCardManChinh.setBackground(new java.awt.Color(254, 204, 213));
        pnCardManChinh.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        jPanel4.setBackground(new java.awt.Color(254, 204, 213));

        tabTang.setBackground(new java.awt.Color(255, 255, 255));

        pnlTang1.setBackground(new java.awt.Color(254, 204, 213));
        pnlTang1.setLayout(new java.awt.GridLayout(1, 1, 15, 15));

        tblTang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phòng", "Loại phòng", "Khách hàng", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTang1.setComponentPopupMenu(jPopupMenu1);
        tblTang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTang1MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblTang1);

        pnlTang1.add(jScrollPane6);

        tabTang.addTab("Tầng 1", pnlTang1);

        jPanel8.setBackground(new java.awt.Color(254, 204, 213));
        jPanel8.setLayout(new java.awt.GridLayout(1, 1, 15, 15));

        tblTang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phòng", "Loại phòng", "Khách hàng", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTang2.setComponentPopupMenu(jPopupMenu1);
        tblTang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTang2MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblTang2);

        jPanel8.add(jScrollPane7);

        tabTang.addTab("Tầng 2", jPanel8);

        jPanel9.setBackground(new java.awt.Color(254, 204, 213));
        jPanel9.setLayout(new java.awt.GridLayout(1, 1, 15, 15));

        tblTang3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phòng", "Loại phòng", "Khách hàng", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTang3.setComponentPopupMenu(jPopupMenu1);
        tblTang3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTang3MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblTang3);

        jPanel9.add(jScrollPane8);

        tabTang.addTab("Tầng 3", jPanel9);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnHuyDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHuyDV.setText("Hủy dịch vụ");

        btnCapNhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCapNhap.setText("Cập nhật");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Dịch vụ của phòng");

        tblDVCP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên DV", "Số lượng", "Đơn giá", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(tblDVCP);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCapNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnHuyDV)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(jLabel12)
                    .addContainerGap(75, Short.MAX_VALUE)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCapNhap, btnHuyDV});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuyDV)
                    .addComponent(btnCapNhap))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel12)
                    .addContainerGap(258, Short.MAX_VALUE)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap(68, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)))
        );

        jPanel5.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên DV", "Số lượng", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(tblDichVu);

        btnThemVaoP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThemVaoP.setText("Thêm vào phòng");
        btnThemVaoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVaoPActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Dịch vụ");

        cboDichVu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboDichVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDichVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThemVaoP))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cboDichVu, 0, 213, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThemVaoP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel7);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(tabTang, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabTang, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnCardManChinh.add(jPanel4);

        jPanel10.setBackground(new java.awt.Color(254, 204, 213));
        jPanel10.setLayout(new java.awt.GridLayout(1, 2, 20, 20));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tổng số giờ hát: ");

        lblGioDung.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGioDung.setText("1.5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("giờ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tiền cần thanh toán");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Tiền khách đưa");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Hình thức thanh toán");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Tiền trả khách");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Trạng thái");

        txtTienCanTT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTienKhachDua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTienKhachDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienKhachDuaActionPerformed(evt);
            }
        });

        txtTienTraKhach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnDoiPhong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDoiPhong.setText("Đổi phòng");

        btnThanhToan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThanhToan.setText("Thanh toán");

        cboHinhThucThanhToan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboHinhThucThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboTrangThaiHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboTrangThaiHoaDon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTraPhong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTraPhong.setText("Trả Phòng");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblGioDung)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(btnTraPhong)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTienTraKhach, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(txtTienKhachDua, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(txtTienCanTT)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(btnDoiPhong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThanhToan))
                            .addComponent(cboHinhThucThanhToan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboTrangThaiHoaDon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(90, 90, 90))
        );

        jPanel11Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDoiPhong, btnThanhToan, btnTraPhong});

        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblGioDung)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTienCanTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboHinhThucThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTienTraKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cboTrangThaiHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoiPhong)
                    .addComponent(btnThanhToan)
                    .addComponent(btnTraPhong))
                .addContainerGap())
        );

        jPanel10.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã HD:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("HÓA ĐƠN CHI TIẾT");

        lblMaHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMaHD.setText("10");

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tiền giờ", "Tiền DV", "Ngày đặt", "Giờ BD", "Giờ KT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tblHoaDon);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(222, 222, 222))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMaHD)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblMaHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.add(jPanel12);

        pnCardManChinh.add(jPanel10);

        pnCardGoc.add(pnCardManChinh, "card1");

        jToolBar2.setRollover(true);
        jToolBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToolBar2.setInheritsPopupMenu(true);
        jToolBar2.setName(""); // NOI18N

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Đăng xuất");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMargin(new java.awt.Insets(2, 50, 2, 14));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton4);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Tài khoản");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMargin(new java.awt.Insets(2, 50, 2, 14));
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton5);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Khách hàng");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setMargin(new java.awt.Insets(2, 50, 2, 14));
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton6);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Phòng");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMargin(new java.awt.Insets(2, 50, 2, 14));
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton7);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Dịch vụ");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setMargin(new java.awt.Insets(2, 50, 2, 14));
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton8);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("Giới thiệu");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setMargin(new java.awt.Insets(2, 50, 2, 14));
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton9);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setText("Thống kê - Doanh thu");
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setMargin(new java.awt.Insets(2, 50, 2, 14));
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton10);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton11.setText("Ghi chú nhanh");
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setMargin(new java.awt.Insets(2, 50, 2, 14));
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton11);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnCardGoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(pnCardGoc, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuTaoDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTaoDHActionPerformed
        jDialogTaoHD.show();
        fillComBoxKhachHang();
    }//GEN-LAST:event_mnuTaoDHActionPerformed

    private void btnTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHoaDonActionPerformed

        if (tabTang.getSelectedIndex() == 0) {
            TaoHoaDon();
        } else if (tabTang.getSelectedIndex() == 1) {
            TaoHoaDon2();
        } else if (tabTang.getSelectedIndex() == 2) {
            TaoHoaDon3();
        }

    }//GEN-LAST:event_btnTaoHoaDonActionPerformed

    private void tblTang3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTang3MouseClicked
        if (evt.getClickCount() == 1) {
            this.index = tblTang3.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                show3();
            }
        }
    }//GEN-LAST:event_tblTang3MouseClicked

    private void tblTang2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTang2MouseClicked
        if (evt.getClickCount() == 1) {
            this.index = tblTang2.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                show2();
            }
        }
    }//GEN-LAST:event_tblTang2MouseClicked

    private void tblTang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTang1MouseClicked
        if (evt.getClickCount() == 1) {
            this.index = tblTang1.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                show1();
            }
        }
    }//GEN-LAST:event_tblTang1MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cboDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDichVuActionPerformed
        // TODO add your handling code here:
        fillToTableDV();
    }//GEN-LAST:event_cboDichVuActionPerformed

    private void btnThemVaoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVaoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemVaoPActionPerformed

    private void txtTienKhachDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienKhachDuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienKhachDuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgnChucvu;
    private javax.swing.ButtonGroup bgnTTDV;
    private javax.swing.ButtonGroup bgnTrangthai;
    private javax.swing.JButton btnCapNhap;
    private javax.swing.JButton btnDoiPhong;
    private javax.swing.JButton btnHuyDV;
    private javax.swing.JButton btnTaoHoaDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemVaoP;
    private javax.swing.JButton btnTraPhong;
    private javax.swing.JComboBox<String> cboDichVu;
    private javax.swing.JComboBox<String> cboHinhThucThanhToan;
    private javax.swing.JComboBox<String> cboKhachHang;
    private javax.swing.JComboBox<String> cboTrangThaiHoaDon;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialogTaoHD;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblGioDung;
    private javax.swing.JLabel lblMaHD;
    private javax.swing.JLabel lblMaPhong;
    private javax.swing.JLabel lblPhongHD;
    private javax.swing.JMenuItem mnuTaoDH;
    private javax.swing.JPanel pnCardGoc;
    private javax.swing.JPanel pnCardManChinh;
    private javax.swing.JPanel pnlTang1;
    private javax.swing.JTabbedPane tabTang;
    private javax.swing.JTable tblDVCP;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTable tblDichVuCS;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblTang1;
    private javax.swing.JTable tblTang2;
    private javax.swing.JTable tblTang3;
    private javax.swing.JTextField txtGiaTheoGioHD;
    private javax.swing.JTextField txtLoaiPhongHD;
    private javax.swing.JTextField txtMaLPHD;
    private javax.swing.JTextField txtTangHD;
    private javax.swing.JTextField txtTienCanTT;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienTraKhach;
    private javax.swing.JTextField txtTrangThaiHD;
    // End of variables declaration//GEN-END:variables

    private void timeBD() {
        tbd = new Thread() {
            @Override
            public void run() {
                SimpleDateFormat date = new SimpleDateFormat("hh:mm:ss");
                while (true) {
                    Date d = new Date();
//                    lblTimeBD.setText(date.format(d));
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        break;
                    }
                }
            }

        };
        tbd.start();
    }

    private void timKT() {
        tkt = new Thread() {
            @Override
            public void run() {
                SimpleDateFormat date = new SimpleDateFormat("hh:mm:ss");
                while (true) {
                    Date d = new Date();
//                    lblTimeKT.setText(date.format(d));
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        break;
                    }
                }
            }

        };
        tkt.start();
    }

    private void dateNow() {
        d = new Thread() {
            @Override
            public void run() {
                SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
                while (true) {
                    Date d = new Date();
//                    lblNgay.setText("Ngày: " + date.format(d));
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        break;
                    }
                }
            }

        };
        d.start();
    }

    PhongService ps = new PhongService();

    private void init() {
        mnuTaoDH.setText("Tạo hóa đơn");
        jDialogTaoHD.setSize(900, 700);
        jDialogTaoHD.setTitle("Quản lý Karaoke - Tạo hóa đơn");
        fillTable1();
        fillTable2();
        fillTable3();
        FillDichVuCS();
//        fillToComboDichVu();
//        fillToTableDichVuHD();
        fillToComboHinhThucTT();
        fillToComboTrangThaiHD();
        System.out.println(UseUtilies.USER.getMaNV());
        fillComboDV();
    }

    private void fillTable1() {
        DefaultTableModel model1 = (DefaultTableModel) tblTang1.getModel();
        model1.setRowCount(0);
        try {
            List<LoaiPhong> lstLP = lps.selectAll();
            for (LoaiPhong lp : lstLP) {
                List<Phong> lst1 = ps.selectByTang(1);
                for (Phong p : lst1) {
                    if (lp.getMaLP().equals(p.getMaLP())) {
                        Object[] row = {
                            p.getMaP(),
                            lp.getTenLP(),
                            //                            p.kh = (String) cboKhachHang.getSelectedItem(),
                            p.kh = null,
                            p.getTrangThai()
                        };
                        model1.addRow(row);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillTable2() {
        DefaultTableModel model1 = (DefaultTableModel) tblTang2.getModel();
        model1.setRowCount(0);
        try {
            List<LoaiPhong> lstLP = lps.selectAll();
            for (LoaiPhong lp : lstLP) {
                List<Phong> lst1 = ps.selectByTang(2);
                for (Phong p : lst1) {
                    if (lp.getMaLP().equals(p.getMaLP())) {
                        Object[] row = {
                            p.getMaP(),
                            lp.getTenLP(),
                            p.kh = (String) cboKhachHang.getSelectedItem(),
                            p.getTrangThai()
                        };
                        model1.addRow(row);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillTable3() {
        DefaultTableModel model1 = (DefaultTableModel) tblTang3.getModel();
        model1.setRowCount(0);
        try {
            List<LoaiPhong> lstLP = lps.selectAll();
            for (LoaiPhong lp : lstLP) {
                List<Phong> lst1 = ps.selectByTang(3);
                for (Phong p : lst1) {
                    if (lp.getMaLP().equals(p.getMaLP())) {
                        Object[] row = {
                            p.getMaP(),
                            lp.getTenLP(),
                            p.kh = (String) cboKhachHang.getSelectedItem(),
                            p.getTrangThai()
                        };
                        model1.addRow(row);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    LoaiPhongService lps = new LoaiPhongService();

    private void show1() {
        try {
            String map = (String) tblTang1.getValueAt(index, 0);
            Phong model = ps.selectByID(map);
            if (model != null) {
                this.setModelTaoHD(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi Show1");
            e.printStackTrace();
        }
    }

    private void show2() {
        try {
            String map = (String) tblTang2.getValueAt(index, 0);
            Phong model = ps.selectByID(map);
            if (model != null) {
                this.setModelTaoHD(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi Show1");
            e.printStackTrace();
        }
    }

    private void show3() {
        try {
            String map = (String) tblTang3.getValueAt(index, 0);
            Phong model = ps.selectByID(map);
            if (model != null) {
                this.setModelTaoHD(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi Show1");
            e.printStackTrace();
        }
    }

    void setModelTaoHD(Phong model) {
        lblMaPhong.setText(model.getMaP());
        lblPhongHD.setText("Phòng " + model.getMaP());
        txtMaLPHD.setText(model.getMaLP() + "");
        String malp = txtMaLPHD.getText();
        LoaiPhong lp = lps.selectByID(malp);
        txtTangHD.setText(model.getTang() + "");
        txtTrangThaiHD.setText(model.getTrangThai() + "");
        txtLoaiPhongHD.setText(lp.getTenLP());
        txtGiaTheoGioHD.setText(lp.getGiaTheoGio() + "");
    }

    private void FillDichVuCS() {
        DefaultTableModel model1 = (DefaultTableModel) tblDichVuCS.getModel();
        model1.setRowCount(0);
        try {
            List<DichVu> lstComBoDV = dvs.selectDVCS();
            for (DichVu dv : lstComBoDV) {
                Object[] row = {
                    dv.getMaDV(),
                    dv.getTenDV(),
                    dv.getSoLuong()
                };
                model1.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

//    private void fillToComboDichVu() {
//        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiDV.getModel();
//        model.removeAllElements();
//        List<LoaiDichVu> listcb = ldvs.selectAll();
//        for (LoaiDichVu ldv : listcb) {
//            model.addElement(ldv);
//        }
//    }

    CTDichVuService ctdv = new CTDichVuService();

//    private void fillToTableDichVuHD() {
//        DefaultTableModel model_dv = (DefaultTableModel) tblDVHienDung.getModel();
//        model_dv.setRowCount(0);
//        try {
//            List<CTDichVu> listctdv = ctdv.selectAll();
//            for (CTDichVu dv : listctdv) {
//                Object[] row = {
//                    dv.getMaDV(),
//                    dv.getTenDV(),
//                    dv.getSoLuong()
//                };
//                model_dv.addRow(row);
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }

    private void fillToComboHinhThucTT() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboHinhThucThanhToan.getModel();
        model.removeAllElements();
        List<ThanhToan> listtt = tts.selectAll();
        for (ThanhToan tt : listtt) {
            model.addElement(tt);
        }
    }

    private void fillToComboTrangThaiHD() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTrangThaiHoaDon.getModel();
        model.removeAllElements();
        List<TrangThaiThanhToan> listtttt = tttts.selectAll();
        for (TrangThaiThanhToan tttt : listtttt) {
            model.addElement(tttt);
        }
    }

//    private void layTime() {
////        HoaDonChiTiet ct = new HoaDonChiTiet();
////        ct.setMaHD(Integer.parseInt(txtMaHD.getText()));
////        ct.setGioBD(dateUtilities.toDate(lblTimeBD.getText()));
////        ct.setMaP((String) tblTang1.getValueAt(index, 0));
////        try {
////            hdcts.update(ct);
////            JOptionPane.showMessageDialog(this, "Bắt đầu thành công");
////        } catch (Exception e) {
////            JOptionPane.showMessageDialog(this, "Bắt đầu thất bại");
////        }
//    }
//
//    private void ktTime() {
////        HoaDonChiTiet ct = new HoaDonChiTiet();
////        ct.setMaHD(Integer.parseInt(txtMaHD.getText()));
////        ct.setGioBD(dateUtilities.toDate(lblTimeKT.getText()));
////        ct.setMaP((String) tblTang1.getValueAt(index, 0));
////        try {
////            hdcts.exitTime(ct);
////            JOptionPane.showMessageDialog(this, "Kết thúc thành công");
////        } catch (Exception e) {
////            JOptionPane.showMessageDialog(this, "Kết thúc thất bại");
////        }
//    }

//    private void showDT() {
////        HoaDonChiTiet ct = new HoaDonChiTiet();
////        ct.getMaHD();
////        ct.getGioBD();
////        ct.getMaP();
////        ct.getGioKT();
////        ct.setTongGio(ct.getGioKT()-ct.getGioBD());
//    }

    private void updateTrangThai() {
        Phong model = getForm();
        try {
            ps.sua(model);
            JOptionPane.showMessageDialog(this, "Trang awn cut");
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    Phong getForm() {
        Phong p = new Phong();
        p.setMaLP(txtMaLPHD.getText());
        p.setTrangThai(2);
        p.setTang(Integer.parseInt(txtTangHD.getText()));
        p.setMaP(lblMaPhong.getText());
        return p;
    }

    private void TaoHoaDon() {
        HoaDon hd = getFormHoaDon();

        Services.HoaDonService hds = new HoaDonService();

        int indext = tblTang1.getSelectedRow();
        try {
            hds.them(hd);
            updateTrangThai();
            JOptionPane.showMessageDialog(this, "Thêm thành công: ");
            tblTang1.setValueAt(cboKhachHang.getSelectedItem(), indext, 2);
            tblTang1.setValueAt("2", indext, 3);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

    }

    private void TaoHoaDon2() {
        HoaDon hd = getFormHoaDon();

        Services.HoaDonService hds = new HoaDonService();

        int indext = tblTang2.getSelectedRow();
        try {
            hds.them(hd);
            updateTrangThai();
            JOptionPane.showMessageDialog(this, "Thêm thành công: ");
            tblTang2.setValueAt(cboKhachHang.getSelectedItem(), indext, 2);
            tblTang2.setValueAt("2", indext, 3);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

    }

    private void TaoHoaDon3() {
        HoaDon hd = getFormHoaDon();

        Services.HoaDonService hds = new HoaDonService();

        int indext = tblTang3.getSelectedRow();
        try {
            hds.them(hd);
            updateTrangThai();
            JOptionPane.showMessageDialog(this, "Thêm thành công: ");
            tblTang3.setValueAt(cboKhachHang.getSelectedItem(), indext, 2);
            tblTang3.setValueAt("2", indext, 3);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

    }

    HoaDon getFormHoaDon() {
        HoaDon hd = new HoaDon();
        KhachHangService khs = new KhachHangService();
        KhachHang kh = (KhachHang) cboKhachHang.getSelectedItem();
        KhachHang kh1 = khs.selectByTen(kh.getTenKH());
        hd.setMaKH(kh1.getMaKH());
        Date d = new Date();
        hd.setNgayDat(convertJavaUtilDateToSqlDate(d));
        hd.setSLPhongDat(1);
        hd.setIDTTPhong(2);

        hd.setMaNV(UseUtilies.USER.getMaNV());

        return hd;
    }

    public java.sql.Date convertJavaUtilDateToSqlDate(java.util.Date date) {
        return new java.sql.Date(date.getTime());
    }

    private void fillComBoxKhachHang() {

        DefaultComboBoxModel cbmodel = (DefaultComboBoxModel) cboKhachHang.getModel();
        cbmodel.removeAllElements();
        KhachHangService khs = new KhachHangService();
        List<KhachHang> lkh = khs.selectAll();
        for (KhachHang khachHang : lkh) {
            cbmodel.addElement(khachHang);
        }
    }

    private void fillToTableDV() {
        DefaultTableModel model = (DefaultTableModel) tblDichVu.getModel();
        model.setRowCount(0);
        try {
            LoaiDichVu loaidv = (LoaiDichVu) cboDichVu.getSelectedItem();
            List<DichVu> listdv = dvs.selectByLoaiDV(loaidv.getMaLDV());
            for (DichVu dv : listdv) {
                Object[] row = {
                    dv.getTenDV(),
                    dv.getSoLuong(),
                    dv.getGiaDV()};
                model.addRow(row);
            }
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Lỗi fillToTableDV");
        }
    }

    private void fillComboDV() {
        try {
            DefaultComboBoxModel model = (DefaultComboBoxModel) cboDichVu.getModel();
            model.removeAllElements();
            List<LoaiDichVu> listdv = ldvs.selectAll();
            for (LoaiDichVu dv : listdv) {
                model.addElement(dv);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi fillComboDV");
        }
    }
}
