package GUI;

import Models.CTHoaDonTam;
import Models.DichVu;
import Models.LoaiDichVu;
import Services.DichVuService;
import Services.LoaiDichVuService;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MainFrame extends javax.swing.JFrame {

    CardLayout card;
    int index;
    Thread tbd, tkt, d;
    LoaiDichVuService ldvs = new LoaiDichVuService();
    DichVuService dvs = new DichVuService();
    ArrayList<CTHoaDonTam> list = new ArrayList();

    public MainFrame() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        timeBD();
        timKT();
        dateNow();
        fillComboDV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgnChucvu = new javax.swing.ButtonGroup();
        bgnTrangthai = new javax.swing.ButtonGroup();
        bgnTTDV = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnCardGoc = new javax.swing.JPanel();
        pnCardManChinh = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lblTimeBD = new javax.swing.JLabel();
        btnBatDau = new javax.swing.JButton();
        lblNgay = new javax.swing.JLabel();
        lblTimeKT = new javax.swing.JLabel();
        btnKetThuc = new javax.swing.JButton();
        lblTrangThai = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cboLoaiDV = new javax.swing.JComboBox<>();
        jPanel22 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jButton33 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jButton35 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnManChinh = new javax.swing.JButton();
        btnTaiKhoan = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnPhong = new javax.swing.JButton();
        btnDichVu = new javax.swing.JButton();
        btnGioiThieu = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        tnGhiChuNhanh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý karaoke - Trang chủ");
        setPreferredSize(new java.awt.Dimension(1000, 705));

        jPanel1.setBackground(new java.awt.Color(254, 204, 213));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        pnCardGoc.setBackground(new java.awt.Color(254, 204, 213));
        pnCardGoc.setLayout(new java.awt.CardLayout());

        pnCardManChinh.setBackground(new java.awt.Color(254, 204, 213));
        pnCardManChinh.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        jPanel4.setBackground(new java.awt.Color(254, 204, 213));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(254, 204, 213));
        jPanel7.setLayout(new java.awt.GridLayout(3, 3, 15, 15));

        jButton1.setText("101");
        jPanel7.add(jButton1);

        jButton2.setText("102");
        jPanel7.add(jButton2);

        jButton3.setText("103");
        jPanel7.add(jButton3);

        jButton4.setText("104");
        jPanel7.add(jButton4);

        jButton5.setText("105");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5);

        jButton6.setText("106");
        jPanel7.add(jButton6);

        jButton7.setText("107");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7);

        jButton8.setText("108");
        jPanel7.add(jButton8);

        jButton9.setText("109");
        jPanel7.add(jButton9);

        jTabbedPane1.addTab("Tầng 1", jPanel7);

        jPanel8.setBackground(new java.awt.Color(254, 204, 213));
        jPanel8.setLayout(new java.awt.GridLayout(3, 3, 15, 15));

        jButton10.setText("201");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton10);

        jButton11.setText("202");
        jPanel8.add(jButton11);

        jButton12.setText("203");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton12);

        jButton13.setText("204");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton13);

        jButton14.setText("205");
        jPanel8.add(jButton14);

        jButton15.setText("206");
        jPanel8.add(jButton15);

        jButton16.setText("207");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton16);

        jButton17.setText("208");
        jPanel8.add(jButton17);

        jButton18.setText("209");
        jPanel8.add(jButton18);

        jTabbedPane1.addTab("Tầng 2", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridLayout(3, 3, 15, 15));

        jButton19.setText("301");
        jPanel9.add(jButton19);

        jButton20.setText("302");
        jPanel9.add(jButton20);

        jButton21.setText("303");
        jPanel9.add(jButton21);

        jButton22.setText("304");
        jPanel9.add(jButton22);

        jButton23.setText("305");
        jPanel9.add(jButton23);

        jButton24.setText("306");
        jPanel9.add(jButton24);

        jButton25.setText("307");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton25);

        jButton26.setText("308");
        jPanel9.add(jButton26);

        jButton27.setText("309");
        jPanel9.add(jButton27);

        jTabbedPane1.addTab("Tầng 3", jPanel9);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pnCardManChinh.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(254, 204, 213));
        jPanel5.setLayout(new java.awt.GridLayout(3, 1));

        jPanel15.setBackground(new java.awt.Color(254, 204, 213));
        jPanel15.setLayout(new java.awt.GridLayout(2, 3, 55, 5));

        lblTimeBD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimeBD.setText("19:05:35");
        jPanel15.add(lblTimeBD);

        btnBatDau.setText("Bắt đầu");
        btnBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatDauActionPerformed(evt);
            }
        });
        jPanel15.add(btnBatDau);

        lblNgay.setText("Ngày: 11/10/2021");
        jPanel15.add(lblNgay);

        lblTimeKT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimeKT.setText("__:__:__");
        jPanel15.add(lblTimeKT);

        btnKetThuc.setText("Kết thúc");
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });
        jPanel15.add(btnKetThuc);

        lblTrangThai.setText("Trạng Thái :Trống");
        jPanel15.add(lblTrangThai);

        jPanel5.add(jPanel15);

        jPanel14.setBackground(new java.awt.Color(254, 204, 213));
        jPanel14.setLayout(new java.awt.GridLayout(2, 3, 55, 15));

        jLabel10.setBackground(new java.awt.Color(254, 204, 213));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Khách hàng");
        jLabel10.setName(""); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(30, 14));
        jPanel14.add(jLabel10);
        jPanel14.add(jTextField2);

        jPanel21.setBackground(new java.awt.Color(254, 204, 213));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel21);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Loại dịch vụ");
        jLabel11.setPreferredSize(new java.awt.Dimension(30, 14));
        jPanel14.add(jLabel11);

        cboLoaiDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiDV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLoaiDVItemStateChanged(evt);
            }
        });
        jPanel14.add(cboLoaiDV);

        jPanel22.setBackground(new java.awt.Color(254, 204, 213));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel22);

        jPanel5.add(jPanel14);

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên mặt hàng", "Giá", "Đơn vị", "Số lượng"
            }
        ));
        jScrollPane3.setViewportView(tblDichVu);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel16);

        pnCardManChinh.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(254, 204, 213));
        jPanel6.setLayout(new java.awt.GridLayout(2, 1));

        jPanel19.setLayout(new java.awt.GridLayout(1, 0));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên dịch vụ", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPane2.setViewportView(tblHoaDon);

        jPanel19.add(jScrollPane2);

        jPanel6.add(jPanel19);

        jPanel20.setBackground(new java.awt.Color(254, 204, 213));
        jPanel20.setLayout(new java.awt.GridLayout(2, 2, 20, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Số giờ đã sử dụng");
        jPanel20.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("0 Giờ");
        jPanel20.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tổng tiền");
        jPanel20.add(jLabel5);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("0 Đồng");
        jPanel20.add(jLabel12);

        jPanel6.add(jPanel20);

        pnCardManChinh.add(jPanel6);

        jPanel10.setLayout(new java.awt.GridLayout(3, 1));

        jPanel11.setLayout(new java.awt.GridLayout(1, 1));

        jPanel18.setBackground(new java.awt.Color(254, 204, 213));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel18);

        jButton33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton33.setText("ĐỔI PHÒNG");
        jPanel11.add(jButton33);

        jPanel17.setBackground(new java.awt.Color(254, 204, 213));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel17);

        jPanel10.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(254, 204, 213));
        jPanel12.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        jButton35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton35.setText("XÓA KHỎI HÓA ĐƠN");
        jPanel12.add(jButton35);

        jButton37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton37.setText("THÊM VÀO HÓA ĐƠN");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton37);

        jPanel10.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(254, 204, 213));
        jPanel13.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        jButton38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton38.setText("THANH TOÁN");
        jPanel13.add(jButton38);

        jButton39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton39.setText("SỬA HÓA ĐƠN");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton39);

        jPanel10.add(jPanel13);

        pnCardManChinh.add(jPanel10);

        pnCardGoc.add(pnCardManChinh, "card1");

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        btnManChinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManChinh.setText("Màn chính");
        btnManChinh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnManChinh.setFocusable(false);
        btnManChinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManChinh.setMargin(new java.awt.Insets(2, 14, 2, 85));
        btnManChinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManChinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManChinhActionPerformed(evt);
            }
        });
        jToolBar1.add(btnManChinh);

        btnTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTaiKhoan.setText("Tài khoản");
        btnTaiKhoan.setFocusable(false);
        btnTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTaiKhoan.setMargin(new java.awt.Insets(2, 14, 2, 85));
        btnTaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTaiKhoan);

        btnKhachHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKhachHang.setText("Khách hàng");
        btnKhachHang.setFocusable(false);
        btnKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhachHang.setMargin(new java.awt.Insets(2, 14, 2, 85));
        btnKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhachHang);

        btnPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPhong.setText("Phòng");
        btnPhong.setFocusable(false);
        btnPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPhong.setMargin(new java.awt.Insets(2, 14, 2, 85));
        btnPhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPhong);

        btnDichVu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDichVu.setText("Dịch vụ");
        btnDichVu.setFocusable(false);
        btnDichVu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDichVu.setMargin(new java.awt.Insets(2, 14, 2, 85));
        btnDichVu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichVuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDichVu);

        btnGioiThieu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGioiThieu.setText("Giới thiệu");
        btnGioiThieu.setFocusable(false);
        btnGioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGioiThieu.setMargin(new java.awt.Insets(2, 14, 2, 85));
        btnGioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnGioiThieu);

        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThongKe.setText("Thống kê doanh thu");
        btnThongKe.setFocusable(false);
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setMargin(new java.awt.Insets(2, 14, 2, 85));
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThongKe);

        tnGhiChuNhanh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tnGhiChuNhanh.setText("Ghi chú nhanh");
        tnGhiChuNhanh.setFocusable(false);
        tnGhiChuNhanh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tnGhiChuNhanh.setMargin(new java.awt.Insets(2, 14, 2, 85));
        tnGhiChuNhanh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tnGhiChuNhanh);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnCardGoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnCardGoc, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton39ActionPerformed

    private void btnBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatDauActionPerformed
        tbd.stop();
    }//GEN-LAST:event_btnBatDauActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        JFrameTaiKhoan frmTK = new JFrameTaiKhoan();
        frmTK.setVisible(true);
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongActionPerformed
        JFramePhong frmP = new JFramePhong();
        frmP.setVisible(true);
    }//GEN-LAST:event_btnPhongActionPerformed

    private void btnManChinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManChinhActionPerformed

    }//GEN-LAST:event_btnManChinhActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        JFrameKhachHang frmKH = new JFrameKhachHang();
        frmKH.setVisible(true);
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichVuActionPerformed
        JFrameDichVu frmDV = new JFrameDichVu();
        frmDV.setVisible(true);
    }//GEN-LAST:event_btnDichVuActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        JFrameThongKe frmTK = new JFrameThongKe();
        frmTK.setVisible(true);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void cboLoaiDVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLoaiDVItemStateChanged
        fillToTableDV();
    }//GEN-LAST:event_cboLoaiDVItemStateChanged

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        try {
            if (tblDichVu.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn dịch vụ");
                return;
            } else {
                String kq = JOptionPane.showInputDialog(this, "Mời nhập số lượng");
                if (kq != null) {
                    for (int row : tblDichVu.getSelectedRows()) {
                        CTHoaDonTam hd = new CTHoaDonTam();
                        hd.setTenDV((String) tblDichVu.getValueAt(index, 0));
                        hd.setSoLuong(Integer.parseInt(kq));
                        hd.setGiaTien((float) tblDichVu.getValueAt(index, 1));
                    }
                    fillToTableHoaDon();
                } else {
                    JOptionPane.showMessageDialog(this, "Bạn chưa nhập số lượng");
                }

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton37ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgnChucvu;
    private javax.swing.ButtonGroup bgnTTDV;
    private javax.swing.ButtonGroup bgnTrangthai;
    private javax.swing.JButton btnBatDau;
    private javax.swing.JButton btnDichVu;
    private javax.swing.JButton btnGioiThieu;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnManChinh;
    private javax.swing.JButton btnPhong;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JComboBox<String> cboLoaiDV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblTimeBD;
    private javax.swing.JLabel lblTimeKT;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnCardGoc;
    private javax.swing.JPanel pnCardManChinh;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JButton tnGhiChuNhanh;
    // End of variables declaration//GEN-END:variables

    private void timeBD() {
        tbd = new Thread() {
            @Override
            public void run() {
                SimpleDateFormat date = new SimpleDateFormat("hh:mm:ss");
                while (true) {
                    Date d = new Date();
                    lblTimeBD.setText(date.format(d));
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        break;
                    }
                }
            }

        };
        tbd.start();
    }

    private void timKT() {
        tkt = new Thread() {
            @Override
            public void run() {
                SimpleDateFormat date = new SimpleDateFormat("hh:mm:ss");
                while (true) {
                    Date d = new Date();
                    lblTimeKT.setText(date.format(d));
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        break;
                    }
                }
            }

        };
        tkt.start();
    }

    private void dateNow() {
        d = new Thread() {
            @Override
            public void run() {
                SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
                while (true) {
                    Date d = new Date();
                    lblNgay.setText("Ngày: " + date.format(d));
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        break;
                    }
                }
            }

        };
        d.start();
    }

    private void fillComboDV() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiDV.getModel();
        model.removeAllElements();
        List<LoaiDichVu> list = ldvs.selectAll();
        for (LoaiDichVu ldv : list) {
            model.addElement(ldv);
        }
    }

    private void fillToTableDV() {
        DefaultTableModel model = (DefaultTableModel) tblDichVu.getModel();
        model.setRowCount(0);
        try {
            LoaiDichVu loaidichvu = (LoaiDichVu) cboLoaiDV.getSelectedItem();
            List<DichVu> list = dvs.selectByLoaiDV(loaidichvu.getMaLDV());
            for (DichVu dv : list) {
                Object[] row = {
                    dv.getTenDV(),
                    dv.getGiaDV(),
                    dv.getDonViTinh(),
                    dv.getSoLuong()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
        }
    }

    private void fillToTableHoaDon() {
        DefaultTableModel model_hd = (DefaultTableModel) tblHoaDon.getModel();
        model_hd.setRowCount(0);
        try {
            ArrayList<CTHoaDonTam> list = new ArrayList();
            for (CTHoaDonTam hd : list) {
                Object[] row = new Object[]{
                    hd.getTenDV(),
                    hd.getSoLuong(),
                    hd.ThanhTien(),};
                model_hd.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
